#include "tsim/city_data.h"

#include <nlohmann/json.hpp>

#include <algorithm>
#include <cmath>

namespace tsim {

namespace {

// game/data/city_data.json, as string pieces (generated by SConstruct).
const char *const kDefaultJson[] = {
#include "city_data_json.inc"
};

using json = nlohmann::json;

double num(const json &j, const char *key, double def) {
	auto it = j.find(key);
	return it != j.end() && it->is_number() ? it->get<double>() : def;
}

int minutes_of(double hours) { return static_cast<int>(std::lround(hours * 60.0)); }

bool parse_day(const json &j, DayPlan &out, std::string *err, const std::string &where) {
	out = DayPlan{};
	if (j.is_null()) return true;
	if (!j.is_object()) {
		if (err) *err = where + ": expected an object";
		return false;
	}
	auto h = j.find("hours");
	if (h == j.end() || !h->is_array() || h->size() != 2) {
		if (err) *err = where + ": hours must be [open, close]";
		return false;
	}
	out.open = true;
	out.open_at = minutes_of((*h)[0].get<double>());
	out.close_at = minutes_of((*h)[1].get<double>());
	auto s = j.find("shifts");
	if (s != j.end() && s->is_array()) {
		for (const json &x : *s) {
			if (!x.is_array() || x.size() != 3) {
				if (err) *err = where + ": each shift is [start, end, staff]";
				return false;
			}
			ShiftSpec sh;
			sh.start = minutes_of(x[0].get<double>());
			sh.end = minutes_of(x[1].get<double>());
			sh.staff = x[2].get<int>();
			if (sh.end <= sh.start || sh.staff <= 0) {
				if (err) *err = where + ": a shift must end after it starts and have staff";
				return false;
			}
			out.shifts.push_back(sh);
		}
	}
	return true;
}

uint32_t hex_color(const json &j, uint32_t def) {
	if (!j.is_string()) return def;
	const std::string s = j.get<std::string>();
	uint32_t v = 0;
	for (char c : s) {
		v <<= 4;
		if (c >= '0' && c <= '9') v |= static_cast<uint32_t>(c - '0');
		else if (c >= 'a' && c <= 'f') v |= static_cast<uint32_t>(c - 'a' + 10);
		else if (c >= 'A' && c <= 'F') v |= static_cast<uint32_t>(c - 'A' + 10);
		else return def;
	}
	return v;
}

} // namespace

const char *building_kind_name(BuildingKind k) {
	switch (k) {
		case BuildingKind::Home:
			return "home";
		case BuildingKind::Shop:
			return "shop";
		case BuildingKind::Office:
			return "office";
	}
	return "home";
}

int BuildingType::headcount(int weekly_hours) const {
	if (!business()) return 0;
	int minutes = 0;
	for (const ShiftSpec &s : weekday.shifts) minutes += s.minutes() * s.staff * 5;
	for (const ShiftSpec &s : weekend.shifts) minutes += s.minutes() * s.staff * 2;
	const int per = std::max(1, weekly_hours) * 60;
	return (minutes + per - 1) / per;
}

const BuildingType *CityData::type(const std::string &id) const {
	const int i = type_index(id);
	return i >= 0 ? &types[static_cast<size_t>(i)] : nullptr;
}

int CityData::type_index(const std::string &id) const {
	for (size_t i = 0; i < types.size(); ++i) {
		if (types[i].id == id) return static_cast<int>(i);
	}
	return -1;
}

const Offering *CityData::offering(const std::string &id) const {
	const int i = offering_index(id);
	return i >= 0 ? &offerings[static_cast<size_t>(i)] : nullptr;
}

int CityData::offering_index(const std::string &id) const {
	for (size_t i = 0; i < offerings.size(); ++i) {
		if (offerings[i].id == id) return static_cast<int>(i);
	}
	return -1;
}

double CityData::urgency(double v) const {
	if (v >= calm_above) return 0.05 * std::max(0.0, 100.0 - v) / std::max(1.0, 100.0 - calm_above);
	if (v >= steep_below) return 0.05 + 0.45 * (calm_above - v) / std::max(1.0, calm_above - steep_below);
	return 0.5 + 1.5 * (steep_below - std::max(0.0, v)) / std::max(1.0, steep_below);
}

bool parse_city_data(const std::string &text, CityData &out, std::string *err) {
	const json j = json::parse(text, nullptr, false);
	if (j.is_discarded() || !j.is_object()) {
		if (err) *err = "city data is not valid JSON";
		return false;
	}
	CityData d;
	if (auto c = j.find("clock"); c != j.end()) {
		d.start_day = static_cast<int>(num(*c, "start_day", d.start_day));
		d.start_hour = static_cast<int>(num(*c, "start_hour", d.start_hour));
	}
	if (auto n = j.find("needs"); n != j.end()) {
		d.hunger_empty_hours = num(*n, "hunger_empty_hours", d.hunger_empty_hours);
		d.energy_empty_hours = num(*n, "energy_empty_hours", d.energy_empty_hours);
		d.asleep_hunger_factor = num(*n, "asleep_hunger_factor", d.asleep_hunger_factor);
		d.pantry_full = num(*n, "pantry_full", d.pantry_full);
	}
	if (auto s = j.find("scoring"); s != j.end()) {
		d.calm_above = num(*s, "calm_above", d.calm_above);
		d.steep_below = num(*s, "steep_below", d.steep_below);
		d.price_weight = num(*s, "price_weight", d.price_weight);
		d.travel_weight = num(*s, "travel_weight_per_minute", d.travel_weight);
		d.closed_penalty = num(*s, "closed_penalty", d.closed_penalty);
		d.closed_memory_days = static_cast<int>(num(*s, "closed_memory_days", d.closed_memory_days));
		d.replan_minutes = std::max(1, static_cast<int>(num(*s, "replan_minutes", d.replan_minutes)));
		d.leave_margin_minutes = static_cast<int>(num(*s, "leave_margin_minutes", d.leave_margin_minutes));
		d.break_minutes = static_cast<int>(num(*s, "break_minutes", d.break_minutes));
	}
	if (auto p = j.find("people"); p != j.end()) {
		d.start_money = num(*p, "start_money", d.start_money);
		if (auto h = p->find("household_sizes"); h != p->end() && h->is_array() && !h->empty()) {
			d.household_sizes.clear();
			for (const json &x : *h) d.household_sizes.push_back(x.get<double>());
		}
		d.weekly_hours = static_cast<int>(num(*p, "weekly_hours", d.weekly_hours));
		d.weekend_dislike = num(*p, "weekend_dislike", d.weekend_dislike);
		d.money_low = num(*p, "money_low", d.money_low);
		d.outside_commute_minutes = static_cast<int>(num(*p, "outside_commute_minutes", d.outside_commute_minutes));
		d.outside_wage = num(*p, "outside_wage", d.outside_wage);
		d.immigrants_per_coach = static_cast<int>(num(*p, "immigrants_per_coach", d.immigrants_per_coach));
		d.shoppers_per_coach = static_cast<int>(num(*p, "shoppers_per_coach", d.shoppers_per_coach));
		d.visitor_early_minutes = static_cast<int>(num(*p, "visitor_arrive_early_minutes", d.visitor_early_minutes));
	}
	if (auto e = j.find("economy"); e != j.end()) {
		d.month_days = std::max(1, static_cast<int>(num(*e, "month_days", d.month_days)));
		d.coach_fare = num(*e, "coach_fare", d.coach_fare);
		d.car_cost_per_km = num(*e, "car_cost_per_km", d.car_cost_per_km);
		d.outside_drive_km = num(*e, "outside_drive_km", d.outside_drive_km);
		d.bus_pass = num(*e, "bus_pass", d.bus_pass);
		d.day_pass_share = num(*e, "day_pass_share", d.day_pass_share);
		d.minutes_per_credit = num(*e, "minutes_per_credit", d.minutes_per_credit);
		d.bike_speed = std::max(0.5, num(*e, "bike_speed", d.bike_speed));
		d.parking_minutes = num(*e, "parking_minutes", d.parking_minutes);
		d.eviction_months = std::max(1, static_cast<int>(num(*e, "eviction_months", d.eviction_months)));
		if (auto l = e->find("location"); l != e->end()) {
			d.centre_factor = num(*l, "centre", d.centre_factor);
			d.edge_factor = num(*l, "edge", d.edge_factor);
			d.edge_distance = std::max(1.0, num(*l, "edge_distance", d.edge_distance));
		}
		if (auto m = e->find("market"); m != e->end()) {
			d.value_years = num(*m, "value_years", d.value_years);
			d.sale_rate = num(*m, "sale_rate", d.sale_rate);
			d.npc_list_chance = num(*m, "npc_list_chance", d.npc_list_chance);
			d.listing_days = static_cast<int>(num(*m, "listing_days", d.listing_days));
		}
		if (auto o = e->find("npc_owners"); o != e->end()) {
			d.price_step = num(*o, "price_step", d.price_step);
			d.wage_step = num(*o, "wage_step", d.wage_step);
			d.rent_step = num(*o, "rent_step", d.rent_step);
			auto range = [&](const char *k, double &lo, double &hi) {
				if (auto r = o->find(k); r != o->end() && r->is_array() && r->size() == 2) {
					lo = (*r)[0].get<double>();
					hi = (*r)[1].get<double>();
				}
			};
			range("price_range", d.price_min, d.price_max);
			range("wage_range", d.wage_min, d.wage_max);
			range("rent_range", d.rent_min, d.rent_max);
		}
	}
	auto offers = j.find("offerings");
	if (offers == j.end() || !offers->is_object()) {
		if (err) *err = "city data needs an offerings table";
		return false;
	}
	for (auto it = offers->begin(); it != offers->end(); ++it) {
		const json &o = it.value();
		Offering of;
		of.id = it.key();
		of.label = o.value("label", of.id);
		of.hunger = num(o, "hunger", 0.0);
		of.energy = num(o, "energy", 0.0);
		of.pantry = num(o, "pantry", 0.0);
		of.pantry_use = num(o, "pantry_use", 0.0);
		of.price = num(o, "price", 0.0);
		of.unlocks = o.value("unlocks", "");
		of.cost = num(o, "cost", 0.0);
		if (!of.unlocks.empty() && of.unlocks != "bike" && of.unlocks != "car") {
			if (err) *err = "offering " + of.id + ": unlocks must be bike or car";
			return false;
		}
		if (auto m = o.find("minutes"); m != o.end() && m->is_array() && m->size() == 2) {
			of.min_minutes = (*m)[0].get<int>();
			of.max_minutes = std::max(of.min_minutes, (*m)[1].get<int>());
		}
		d.offerings.push_back(of);
	}
	auto types = j.find("buildings");
	if (types == j.end() || !types->is_object()) {
		if (err) *err = "city data needs a buildings table";
		return false;
	}
	for (auto it = types->begin(); it != types->end(); ++it) {
		const json &b = it.value();
		BuildingType t;
		t.id = it.key();
		t.label = b.value("label", t.id);
		const std::string kind = b.value("kind", "home");
		if (kind == "home") t.kind = BuildingKind::Home;
		else if (kind == "shop") t.kind = BuildingKind::Shop;
		else if (kind == "office") t.kind = BuildingKind::Office;
		else {
			if (err) *err = "building " + t.id + ": unknown kind " + kind;
			return false;
		}
		if (auto s = b.find("size"); s != b.end() && s->is_array() && s->size() == 2) {
			t.width = (*s)[0].get<double>();
			t.depth = (*s)[1].get<double>();
		}
		t.households = static_cast<int>(num(b, "households", 0));
		t.rent = num(b, "rent", 0.0);
		t.price = num(b, "price", 0.0);
		if (auto o = b.find("offers"); o != b.end() && o->is_array()) {
			for (const json &x : *o) {
				const std::string id = x.get<std::string>();
				if (d.offering_index(id) < 0) {
					if (err) *err = "building " + t.id + ": unknown offering " + id;
					return false;
				}
				t.offers.push_back(id);
			}
		}
		t.slots = static_cast<int>(num(b, "slots", 0));
		t.desks = static_cast<int>(num(b, "desks", 0));
		t.wage = num(b, "wage", 0.0);
		t.revenue = num(b, "revenue", t.kind == BuildingKind::Office ? 1.5 * t.wage : 0.0);
		t.value = num(b, "value", 0.0);
		if (auto w = b.find("weekday"); w != b.end() && !parse_day(*w, t.weekday, err, t.id + " weekday")) return false;
		if (auto w = b.find("weekend"); w != b.end() && !parse_day(*w, t.weekend, err, t.id + " weekend")) return false;
		t.min_staff = std::max(1, static_cast<int>(num(b, "min_staff", 1)));
		t.parking = b.value("parking", "none");
		if (auto c = b.find("color"); c != b.end()) t.color = hex_color(*c, t.color);
		t.city = b.value("city", false);
		if (t.kind == BuildingKind::Home && t.households <= 0) {
			if (err) *err = "home " + t.id + " needs households";
			return false;
		}
		d.types.push_back(t);
	}
	// Fixed order (JSON objects are sorted by key) so indices are stable.
	out = std::move(d);
	return true;
}

const std::string &default_city_data_json() {
	static const std::string text = [] {
		std::string s;
		for (const char *p : kDefaultJson) s += p;
		return s;
	}();
	return text;
}

const CityData &default_city_data() {
	static const CityData data = [] {
		CityData d;
		std::string err;
		parse_city_data(default_city_data_json(), d, &err);
		return d;
	}();
	return data;
}

} // namespace tsim
